config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get 'contact-us', to: 'messages#new', as: 'new_message'
  post 'contact-us', to: 'messages#create', as: 'create_message'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :courses
  resources :locations
  resources :categories
  #get  '/help',    to: 'static_pages#help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post   'courses/:id/upvote',     to: 'upvotes#new', as: 'upvote'
  post   'courses/:id/downvote',  to: 'downvotes#new', as: 'downvote'
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/422", :to => "errors#unacceptable", :via => :all
  match "/500", :to => "errors#internal_error", :via => :all
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1 class="text-center">Welcome to Your Course App</h1>
  <p class="text-center">This is the home page for the RAD Assignment 2</p> 
</div>
<div class="row">
  <div class="col-xs-12 col-md-4">
    <div class="well block margin-bottom-three">
      <h3 class="text-center margin-top-none">Register for an account</h3>
      <p>Visit here to register for a RMIT Coordinator Account</p>
      <%= link_to 'Sign up now', signup_path, class: 'btn btn-primary btn-block' %>
    </div>
  </div>
  <div class="col-xs-12 col-md-4">
    <div class="well block margin-bottom-three">
      <h3 class="text-center margin-top-none">Sign in to your account</h3>
      <p>Visit here to sign in to your existing coordinator account.</p>
      <%= link_to 'Log in to your account', login_path, class: 'btn btn-primary btn-block' %>
    </div>
  </div>
  <div class="col-xs-12 col-md-4">
    <div class="well block margin-bottom-three">
      <h3 class="text-center margin-top-none">View Course as Guest User</h3>
      <p>Click here to view the current RMIT courses as a guest user.</p>
      <%= link_to 'Browse all courses', courses_path, class: 'btn btn-primary btn-block' %>
    </div>
  </div>
</div>