config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get 'contact-us', to: 'messages#new', as: 'new_message'
  post 'contact-us', to: 'messages#create', as: 'create_message'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :courses
  resources :locations
  resources :categories
  #get  '/help',    to: 'static_pages#help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post   'courses/:id/upvote',     to: 'upvotes#new', as: 'upvote'
  post   'courses/:id/downvote',  to: 'downvotes#new', as: 'downvote'
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/422", :to => "errors#unacceptable", :via => :all
  match "/500", :to => "errors#internal_error", :via => :all
end

app/views/shared/_course.html.erb
<div class="clearfix well">
  <div class="float_left padding_right">
  <!--Course Image-->
    <%= image_tag course.image, class: 'thumbnail', size: "300x250" %>
  </div>
  <div class="">
    <!--Course Name-->
    <h3><%= link_to course.name, course_path(:id => course.id)%></h3>
    <!--Course Coordinator-->
    <p><strong>Coordinator:</strong>
    <% if course.user.present? %>
      <%= link_to course.user.name, user_path(course.user.id) %>
    <% else %>
      No Coordinator
    <% end %>
    </p>
    <!--Prerequisites-->
    <p><strong>Prerequisite:</strong>
    <%= course.prerequisite %>
    </p>
    <!--Locations-->
    <% if course.locations.present? %>
      <p><strong>Locations:</strong>
        <%= course.locations.collect { |c| link_to c.name, location_path(c.id) }.join(", ").html_safe %>
      </p>
    <% else %>
      <p><strong>Locations:</strong><br>
      No Locations</p>
    <% end %>
    <!--Categories-->
    <% if course.categories.present? %>
      <p><strong>Categories:</strong>
        <%= course.categories.collect { |c| link_to c.name, category_path(c.id) }.join(", ").html_safe %>
      </p>
    <% else %>
      <p><strong>Categories:</strong> No Categories</p>
    <% end %>
    <!--Created-->
    <p><strong>Created:</strong> <%= elapsed_time(course.created_at) %> ago
    <!--Updated-->
    <strong>Updated:</strong> <%= elapsed_time(course.updated_at) %> ago</p>
    <div class="pull-right">
      <%= render 'shared/thumbs', course: course %>
    </div>
  </div>
</div>

app/views/shared/_courses.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#Courses">Courses</a></li>
  <li><a data-toggle="tab" href="#Coordinators">Coordinators</a></li>
</ul>

<div class="tab-content">
  <div id="Courses" class="tab-pane fade in active">
    <% courses.each do |course| %>
      <%= render 'shared/course', course: course %>
    <% end %>
  </div>
  <div id="Coordinators" class="tab-pane fade">
    <% courses.select(:user_id).distinct.each do |course| %>
      <%= render 'shared/user', course: course %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_page.html.erb
<div class="error">
  <h1 class="error__heading">
    <%= heading %>
  </h1>
  <p class="error__message">
    <%= message %>
  </p>
</div>

app/views/shared/_thumbs.html.erb
<%= link_to upvote_path(course.id), method: :post, class: 'btn', title: "Upvote #{course.name}" do %>
  <span class="fa fa-thumbs-o-up fa-lg" aria-hidden="true"></span>  <%= Upvote.where(course_id: course.id).count %>
<% end %>
<%= link_to downvote_path(course.id), method: :post, class: 'btn btn-danger', title: "Downvote #{course.name}" do %>
  <span class="fa fa-thumbs-o-down fa-lg" aria-hidden="true"></span>  <%= Downvote.where(course_id: course.id).count %>
<% end %>

app/views/shared/_user.html.erb
<% if course.user.present? %>
  <div class="clearfix well">
    <div class="float_left padding_right">
      <%= gravatar_for course.user, size: 220 %>
    </div>
    <div class="">
      <!--Course Coordinator Name-->
      <h3><%= link_to course.user.name, user_path(:id => course.user.id)%></h3>
      <!--Course Coordinator Email-->
      <p><strong>Coordinator Email: </strong><%= course.user.email %></p>
      <!--Courses-->
      <p><strong>Courses:</strong>
        <%= course.user.courses.collect { |c| link_to c.name, course_path(c.id) }.join(", ").html_safe %>
      </p>
      <!--Admin-->
      <% if is_admin? %>
        <p><strong>Is Admin:</strong>
        <% if course.user.admin? %>
          Yes
        <% else %>
          No
        <% end %>
      <% end %>
      </p>
    </div>
  </div>
<% else %>
<% end %>