config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get 'contact-us', to: 'messages#new', as: 'new_message'
  post 'contact-us', to: 'messages#create', as: 'create_message'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :courses
  resources :locations
  resources :categories
  #get  '/help',    to: 'static_pages#help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post   'courses/:id/upvote',     to: 'upvotes#new', as: 'upvote'
  post   'courses/:id/downvote',  to: 'downvotes#new', as: 'downvote'
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/422", :to => "errors#unacceptable", :via => :all
  match "/500", :to => "errors#internal_error", :via => :all
end

app/models/category.rb
class Category < ApplicationRecord
  # Relationships
  has_and_belongs_to_many :courses

  # REGEX
  VALID_CATEGORY_REGEX = /\A[\w\d\s]+\z/

  # Name
  validates :name,
    presence: true,
    length: {
      minimum: 2,
      maximum: 50,
      too_short: 'Category is to short (minimum is %{count} characters)',
      too_long: 'Category is to long (maximum is %{count} characters)'
    },
    format: {
      with: VALID_CATEGORY_REGEX,
      message: 'Category is invalid syntax.'
    },
    uniqueness: {
      case_sensitive: false
  }
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # Checking Permissions
  before_action :logged_users_only, except: [:index, :show]
  before_action :admin_only, only: [:destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    set_category
    @courses = @category.courses
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    set_category
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, flash: {success: "Successfully created #{@category.name} category!" }}
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    set_category

    respond_to do |format|
      if @category.update_attributes(category_params)
        format.html { redirect_to @category, flash: {success: "Successfully updated #{@category.name} category!" }}
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    set_category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, flash: {success: "Successfully deleted #{@category.name} category!" }}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit([:name])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="form">
    <%= form_for category, url: url, method: method do |f| %>
        <%= render 'shared/error_messages', object: category %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control', placeholder: 'Category Name' %>
        </div>
        <%= f.submit class: 'btn btn-primary btn-block' %>
    <% end %>
</div>

app/views/categories/edit.html.erb
<% provide(:title, 'Edit Category') %>
<h1>Edit <%= @category.name %> category</h1>
<p class="lead">Enter a name for a category.</p>
<%= render 'form', category: @category, url: category_path(@category), method: :put %>

app/views/categories/index.html.erb
<% provide(:title, 'All Categories') %>
 <% if (@categories.present?) %>
  <h1 class="text-center page_header">All Categories</h1>
  <h5 class="text-center">List of all categories available.</h5>
  <table class="table table-hover block">
    <thead>
      <tr>
        <th>Name</th>
        <th class="text-center">Courses</th>
        <th>Latest Course</th>
        <th class="text-center">Date Added</th>
        <th class="text-center">Last Updated</th>
        <% if (logged_in?) %>
          <th class="text-right"><span class="fa fa-cogs fa-lg" aria-hidden="true"></span></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |c| %>
      <% course = c.courses.order(:updated_at).last %>
      <tr>
        <td><%= link_to c.name, category_path(c.id) %></td>
        <td class="text-center"><%= c.courses.count %></td>
        <td>
          <% if (course.present?) %>
            <%= link_to course.name, course_path(course.id) %>
          <% else %>
            None
          <% end %>
        </td>
        <td class="text-center"><%= c.created_at.strftime("%d/%m/%Y") %></td>
        <td class="text-center"><%= "#{elapsed_time(c.updated_at)} ago" %></td>
        <% if (logged_in?) %>
          <td class="text-right">
            <%= link_to edit_category_path(c.id), title: "Edit #{c.name}" do %>
                <span class="fa fa-pencil-square-o fa-lg" aria-hidden="true"></span>
            <% end %>
            <% if (current_user.admin?) %>
              <%= link_to category_path(c.id), method: :delete, title: "Delete #{c.name}", data: { confirm: "Are you sure?" } do %>
                <span class="fa fa-trash-o fa-lg" aria-hidden="true"></span>
              <% end %>
            <% end %>
          </td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <%= render 'shared/error_page', heading: 'Locations Not Found', message: 'Cannot find any locations within the application. Please create one by logging in as a user.' %>
<% end %>

app/views/categories/new.html.erb
<% provide(:title, 'New Category') %>
<h1>Create a new category</h1>
<h4>Enter the name for a new category</h4>
<%= render 'form', category: @category, url: categories_path, method: :post %>

app/views/categories/show.html.erb
<% provide(:title, @category.name) %>
<% if (@courses.present?) %>
  <h1 class="text-center page_header"><%= @category.name %></h1>
  <%= render 'shared/courses', courses: @courses %>
<% else %>
  <%= render 'shared/error_page', heading: 'Courses Not Found', message: "Cannot find any courses in #{@category.name}. Please create one by logging in as a user." %>
<% end %>