config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  
  get 'contact-us', to: 'messages#new', as: 'new_message'
  post 'contact-us', to: 'messages#create', as: 'create_message'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :courses
  resources :locations
  resources :categories
  #get  '/help',    to: 'static_pages#help'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post   'courses/:id/upvote',     to: 'upvotes#new', as: 'upvote'
  post   'courses/:id/downvote',  to: 'downvotes#new', as: 'downvote'
  
  match "/404", :to => "errors#not_found", :via => :all
  match "/422", :to => "errors#unacceptable", :via => :all
  match "/500", :to => "errors#internal_error", :via => :all
end

app/views/layouts/_flash.html.erb
  <% flash.each do |message_type, message| %>
    <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <small>
      <a href="https://www.rmit.edu.au/" target="_blank">RMIT</a> <a href="http://www1.rmit.edu.au/courses/051833" target="_blank">RAD</a> Assignment Stage 1 & 2 By <a href="https://github.com/rmit-s3530160-elliot-schot" target="_blank">Elliot Schot</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Contact", new_message_url %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="heading">
  <div class="container">
    <% if logged_in? %>
      <%= link_to "YourCourseApp", courses_path, class: "navbar-brand" %>
    <% else %>
      <%= link_to "YourCourseApp", root_path, class: "navbar-brand" %>
    <% end %>
  </div>
</div>
<!--WHOLE Navbar START-->
<nav class="navbar navbar-default">
  <div class="container">
    <!--Left Navbar START-->
    <ul class="nav navbar-nav">
      <!--Categories Dropdown START-->
      <li class="dropdown">
        <a href="/categories" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% @categories.each do |category| %>
            <li><%= link_to category.name, category %></li>
          <% end %>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'All Categories', categories_path %></li>
          <% if logged_in? %>
            <li><%= link_to 'Create Category', new_category_path %></li>
          <% end %>
        </ul>
      </li>
      <!--Categories Dropdown END-->
      <!--Locations Dropdown START-->
      <li class="dropdown">
        <a href="/locations" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Locations <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% @locations.each do |location| %>
            <li><%= link_to location.name, location %></li>
          <% end %>
          <li role="separator" class="divider"></li>
          <li><%= link_to 'All Locations', locations_path %></li>
          <% if logged_in? %>
            <li><%= link_to 'Create Location', new_location_path %></li>
          <% end %>
        </ul>
      </li>
      <!--Locations Dropdown END-->
      <!--Courses Dropdown START-->
      <li class="dropdown">
        <a href="/courses" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Courses <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'All Courses', courses_path %></li>
          <% if logged_in? %>
            <li><%= link_to 'Create Course', new_course_path %></li>
          <% end %>
        </ul>
      </li>
      <!--Courses Dropdown END-->
    </ul>
    <!--Left Navbar END-->
    <!--Right Navbar START-->
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Contact Us", new_message_url, class: 'nav-item' %></li>
      <% if logged_in? %>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><%= link_to "View Profile", user_path(current_user) %></li>
          <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
          <li><%= link_to "All Coordinators", users_path %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        </ul>
      </li>
      <% else %>
        <li><%= link_to "Log In", login_path, class: 'nav-item' %></li>
      <% end %>
    </ul>
    <!--Right Navbar END-->
  </div>
</nav>
<!--WHOLE Navbar END-->

app/views/layouts/_refs.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/refs' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <%= render 'layouts/flash' %>
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <div class="container">
    <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>